apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations: {}
  labels:
    app: servicemesh-full-node-c
    app.kubernetes.io/instance: servicemesh-full-node-c
    app.kubernetes.io/name: sm-component
    kubevirt.io/dynamic-credentials-support: 'true'
  name: servicemesh-full-vmi-c
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: servicemesh-full-vmi-c 
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: servicemesh-full-vmi-c 
        kubevirt.io/size: small
        app: servicemesh-full-node-c
        app.kubernetes.io/instance: servicemesh-full-node-c
        app.kubernetes.io/name: sm-component
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: servicemesh-full-vmi-c 
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
              write_files:
                - path: /opt/install_app.sh
                  content: IyEvYmluL2Jhc2gKY3VybCAtc0wgaHR0cHM6Ly9ycG0ubm9kZXNvdXJjZS5jb20vc2V0dXBfMTgueCB8IGJhc2ggLSAKZG5mIGluc3RhbGwgbm9kZWpzIGdpdCB0Y3BkdW1wIC15CmdpdCBjbG9uZSBodHRwczovL2dpdGh1Yi5jb20vY2FzaW1vbi1yaC9zZXJ2aWNlbWVzaC1mdWxsLWRlbW8uZ2l0CmNkIHNlcnZpY2VtZXNoLWZ1bGwtZGVtby9zbS1jb21wb25lbnQtY29kZQpucG0gaQpucG0gcnVuIGJ1aWxkCg==
                  encoding: b64
                  permissions: '0755'
                  owner: fedora:fedora          
                - path: /etc/environment
                  content: |
                    JUMPS=6
                    ID=C
                    CHAIN_SVC=http://servicemesh-full-node-d:3000/chain
                    JAEGER_COLLECTOR_ENDPOINT=http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces
              runcmd:
                - source /etc/environment
          name: cloudinitdisk
