apiVersion: v1
kind: Service
metadata:
  name: svc-serviced-vm
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    kubevirt.io/domain: serviced-vm
  sessionAffinity: None
  type: ClusterIP