replicaCount: 1

image:
  name: servicemesh-full-node
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: "servicemesh-full-node-a"

env:
  - name: JUMPS
    value: "6"
  - name: ID
    value: "A"
  - name: CHAIN_SVC
    value: "http://servicemesh-full-node-b:3000/chain"
  - name: JAEGER_COLLECTOR_ENDPOINT
    value: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"

service:
  type: ClusterIP
  port: 3000
route:
  enable: true
  wildcardDomain: ""

extraLabels:
  - app.kubernetes.io/part-of: servicemesh-node
  - app.openshift.io/runtime: nodejs


servicemesh:
  gateway: "servicemesh-node"
  subset: v1